from typing import Any


CITY_DATA: dict[str, dict[str, list[dict[str, Any]]]] = {
    "서울": {"attractions": [{"name": "경복궁", "description": "조선 시대 궁궐의 풍경을 볼 수 있는 장소입니다.", "latitude": 37.5796, "longitude": 126.977, "category": "궁궐"}], "restaurants": [{"name": "광화문 한식당", "description": "궁궐 관람 뒤 들르기 좋은 한식 식당입니다.", "latitude": 37.5759, "longitude": 126.9768, "estimated_price_krw": 15000}]},
    "부산": {"attractions": [{"name": "해운대해수욕장", "description": "바다 산책과 해변 풍경을 즐길 수 있습니다.", "latitude": 35.1587, "longitude": 129.1604, "category": "해변"}], "restaurants": [{"name": "해운대 돼지국밥", "description": "부산 대표 국밥을 맛볼 수 있는 식당입니다.", "latitude": 35.1631, "longitude": 129.1635, "estimated_price_krw": 10000}]},
    "제주": {"attractions": [{"name": "성산일출봉", "description": "제주 동쪽의 화산 지형과 바다를 볼 수 있습니다.", "latitude": 33.458, "longitude": 126.9425, "category": "자연"}], "restaurants": [{"name": "성산 고기국수", "description": "제주식 고기국수를 맛볼 수 있는 식당입니다.", "latitude": 33.4591, "longitude": 126.9368, "estimated_price_krw": 11000}]},
    "강릉": {"attractions": [{"name": "경포해변", "description": "동해 바다와 넓은 백사장을 즐길 수 있습니다.", "latitude": 37.8057, "longitude": 128.907, "category": "해변"}], "restaurants": [{"name": "초당순두부 마을", "description": "강릉의 부드러운 순두부를 맛볼 수 있습니다.", "latitude": 37.7916, "longitude": 128.9147, "estimated_price_krw": 12000}]},
    "인천": {"attractions": [{"name": "송도 센트럴파크", "description": "도심 공원과 수변 산책로를 즐길 수 있습니다.", "latitude": 37.392, "longitude": 126.639, "category": "공원"}], "restaurants": [{"name": "송도 해산물 식당", "description": "인천의 신선한 해산물을 맛볼 수 있습니다.", "latitude": 37.3914, "longitude": 126.6412, "estimated_price_krw": 22000}]},
    "대전": {"attractions": [{"name": "한밭수목원", "description": "도심 속 계절별 식물을 관찰할 수 있습니다.", "latitude": 36.3674, "longitude": 127.3888, "category": "수목원"}], "restaurants": [{"name": "대전 칼국수", "description": "대전식 칼국수를 맛볼 수 있는 식당입니다.", "latitude": 36.3504, "longitude": 127.3845, "estimated_price_krw": 9000}]},
    "대구": {"attractions": [{"name": "김광석다시그리기길", "description": "벽화와 음악을 테마로 한 골목입니다.", "latitude": 35.8593, "longitude": 128.6061, "category": "문화거리"}], "restaurants": [{"name": "대구 막창 골목", "description": "대구식 막창을 맛볼 수 있는 식당입니다.", "latitude": 35.8704, "longitude": 128.5911, "estimated_price_krw": 18000}]},
    "광주": {"attractions": [{"name": "국립아시아문화전당", "description": "전시와 공연을 즐길 수 있는 복합 문화 공간입니다.", "latitude": 35.146, "longitude": 126.921, "category": "문화"}], "restaurants": [{"name": "광주 떡갈비", "description": "광주식 떡갈비를 맛볼 수 있는 식당입니다.", "latitude": 35.1472, "longitude": 126.9179, "estimated_price_krw": 19000}]},
    "전주": {"attractions": [{"name": "전주한옥마을", "description": "전통 한옥과 골목 풍경을 즐길 수 있습니다.", "latitude": 35.815, "longitude": 127.153, "category": "한옥마을"}], "restaurants": [{"name": "전주비빔밥", "description": "전주식 비빔밥을 맛볼 수 있는 식당입니다.", "latitude": 35.814, "longitude": 127.152, "estimated_price_krw": 13000}]},
    "경주": {"attractions": [{"name": "동궁과 월지", "description": "야경이 아름다운 신라 시대 유적입니다.", "latitude": 35.8347, "longitude": 129.2269, "category": "역사유적"}], "restaurants": [{"name": "경주 황남빵 카페", "description": "경주 대표 간식과 음료를 즐길 수 있습니다.", "latitude": 35.8377, "longitude": 129.2148, "estimated_price_krw": 8000}]},
}
